### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Atomosk** [rexim/empty-repo-for-ForNeVeR-to-star#3]

**Comment by ForNeVeR** [comment]
Today I suggest to use [ABRMS](|https://github.com/landondyer/kasm/blob/master/LICENSE).

**Comment by rexim** [comment]
I believe that Emptiness is Public Domain. Should we state that explicitly?

**Comment by ForNeVeR** [comment]
@Minoru could argue again.

**Comment by ForNeVeR** [comment]
Also our right to deny people from using Emptiness could be a big tactical advantage.

**Comment by rexim** [comment]
ABRMS it is then.
